robots:
  - name: bot1
    x_pose: "-1.5"
    y_pose: "-0.5"
    z_pose: 0.1
    enabled: true
  - name: bot2
    x_pose: "-1.5"
    y_pose: "0.5"
    z_pose: 0.01
    enabled: false
  - name: bot3
    x_pose: "1.5"
    y_pose: "-0.5"
    z_pose: 0.1
    enabled: true
  - name: bot4
    x_pose: "1.5"
    y_pose: "0.5"
    z_pose: 0.01
    enabled: false